version: '3.0'
services:
  api:
    build: ./server/
    container_name: api
    ports:
      - "3700:3700"
    command: npm start  
    environment:
      MONGO_URI: mongodb://rania:rania@db:27017
    volumes:
      - "./server/:/app"  
      - "/app/node_modules"
    networks:
      - test_network
  web:
    build: ./client/
    container_name: web
    command: npm start  
    volumes:
      - web-root:/app/build
      - "./client/:/app"  
      - "/app/node_modules"
    networks:
      - test_network
  db: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rania
      MONGO_INITDB_ROOT_PASSWORD: rania
    volumes:
      - db-data:/data/db
    networks:
      - test_network
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      -"443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api
      - web
    networks:
      - test_network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email trabelsirania60@gmail.com --agree-tos --no-eff-email --staging -d tesstt4.ddns.net
    networks:
      - test_network

volumes:
  db-data: {} 
  certbot-etc:
  certbot-var:
  web-root:
    driver: local

networks:
  test_network:
    driver: bridge
