name: CI/CD Pipeline

on:
  push:
    branches: [ "version1","version2" ]
  pull_request:
    branches: [ "master" ]

jobs:
  continuous_integrate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Transfer all project files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OVH_ADDRESS }}
          username: ${{ secrets.OVH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: .
          target: /home/ubuntu/deployements/
          
      - name: Debug directory structure
        run: |
          ls -R

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      
          

   

  continuos_deployment:
    needs: continuous_integrate
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Deployment steps
      - name: Execute SSH Commands for Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OVH_ADDRESS }}
          username: ${{ secrets.OVH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/dockercrud/
            sudo docker-compose down
            sudo docker-compose up --build -d
 
